# Generated by Django 5.0.7 on 2024-08-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("email", models.CharField(max_length=48)),
                ("phoneNumber", models.CharField(max_length=48)),
                ("isAdmin", models.CharField(max_length=1)),
            ],
        ),
    ]
